
let menuData = loadMenuData();
let drinks = menuData.drinks.filter(d=>d.visible!==false);
const i18n = {
  en:{brandSub:"AI Cocktail Experience",navAI:"AI Bartender",navMenu:"Full Menu",navRituals:"Rituals",since:"A NIGHT OUT · SINCE 2007",heroTitle:"Tell us how you want to feel tonight.",heroLead:"Choose your mood, flavour and strength. The Sign AI Bartender will match you with the right drink.",findDrink:"Find my drink",seeAll:"See all drinks",romantic:"♥ Romantic",party:"✦ Party",fresh:"◌ Fresh",adventurous:"⚡ Adventurous",tonightSignature:"Tonight's signature",flowerBombSub:"Elderflower · Tequila · Agave · Umami",yourAI:"YOUR AI BARTENDER",threeChoices:"Three choices. One perfect match.",mood:"Mood",romanticPlain:"Romantic",partyPlain:"Party",freshPlain:"Fresh",adventurousPlain:"Adventurous",classic:"Classic",surprise:"Surprise me",taste:"Taste",choose3:"Choose up to 3",sweet:"Sweet",sour:"Sour",bitter:"Bitter",spicy:"Spicy",smoky:"Smoky",strength:"Strength",easy:"Easy",balanced:"Balanced",strong:"Strong",recommend:"Recommend my cocktail",aiMatch:"AI MATCH",yourRec:"YOUR RECOMMENDATION",another:"Show another",addOrder:"Add to order",fullMenu:"FULL MENU",smartMenu:"Every drink. One smart menu.",searchPlaceholder:"Search cocktail, flavour or category",ritualEyebrow:"A LITTLE RITUAL WORTH KEEPING",ritualTitle:"Every night has its own story.",aperitivoDate:"Aperitivo Date",aperitivoText:"Raise a glass to gossip. Selected aperitivo highlights.",signatureTasting:"Signature Tasting",signatureText:"Choose three drinks from the tasting menu.",musicBingo:"Music Bingo",musicText:"Recognise the track, mark your card and play.",cheers:"Cheers & Shenanigans",cheersText:"Music, theatre, cocktails and late-night energy.",bartenderChoice:"Bartender Choice",bartenderText:"No menu, no limits. Let the bartender create.",yourOrder:"Your Order",total:"Total",sendStaff:"Send to staff",order:"Order",added:"added",empty:"Your order is empty.",ready:"Recommendation ready",sweetBar:"Sweet",freshBar:"Fresh",boldBar:"Bold",curiousBar:"Curious"},
  de:{brandSub:"KI-Cocktail-Erlebnis",navAI:"KI-Barkeeper",navMenu:"Gesamte Karte",navRituals:"Wochenprogramm",since:"A NIGHT OUT · SEIT 2007",heroTitle:"Wie möchtest du dich heute Abend fühlen?",heroLead:"Wähle Stimmung, Geschmack und Stärke. Der KI-Barkeeper von The Sign findet den passenden Drink für dich.",findDrink:"Meinen Drink finden",seeAll:"Alle Drinks ansehen",romantic:"♥ Romantisch",party:"✦ Party",fresh:"◌ Frisch",adventurous:"⚡ Abenteuerlustig",tonightSignature:"Signature des Abends",flowerBombSub:"Holunderblüte · Tequila · Agave · Umami",yourAI:"DEIN KI-BARKEEPER",threeChoices:"Drei Entscheidungen. Ein perfekter Match.",mood:"Stimmung",romanticPlain:"Romantisch",partyPlain:"Party",freshPlain:"Frisch",adventurousPlain:"Abenteuerlustig",classic:"Klassisch",surprise:"Überrasch mich",taste:"Geschmack",choose3:"Bis zu 3 auswählen",sweet:"Süß",sour:"Sauer",bitter:"Bitter",spicy:"Scharf",smoky:"Rauchig",strength:"Stärke",easy:"Leicht",balanced:"Ausgewogen",strong:"Stark",recommend:"Cocktail empfehlen",aiMatch:"KI-MATCH",yourRec:"DEINE EMPFEHLUNG",another:"Weitere Empfehlung",addOrder:"Zur Bestellung hinzufügen",fullMenu:"GESAMTE KARTE",smartMenu:"Alle Drinks. Eine smarte Karte.",searchPlaceholder:"Cocktail, Geschmack oder Kategorie suchen",ritualEyebrow:"EIN KLEINES RITUAL, DAS BLEIBT",ritualTitle:"Jeder Abend erzählt seine eigene Geschichte.",aperitivoDate:"Aperitivo Date",aperitivoText:"Ein Glas, gute Gespräche und ausgewählte Aperitivo-Highlights.",signatureTasting:"Signature Tasting",signatureText:"Wähle drei Drinks aus dem Tasting-Menü.",musicBingo:"Music Bingo",musicText:"Song erkennen, Karte markieren und mitspielen.",cheers:"Cheers & Shenanigans",cheersText:"Musik, Show, Cocktails und Late-Night-Energie.",bartenderChoice:"Bartender Choice",bartenderText:"Keine Karte, keine Grenzen. Lass den Barkeeper kreieren.",yourOrder:"Deine Bestellung",total:"Gesamt",sendStaff:"An das Team senden",order:"Bestellung",added:"hinzugefügt",empty:"Deine Bestellung ist leer.",ready:"Empfehlung ist bereit",sweetBar:"Süß",freshBar:"Frisch",boldBar:"Kräftig",curiousBar:"Abenteuer"}
};
const grid=document.getElementById('menuGrid'),filters=document.getElementById('filters'),search=document.getElementById('search');
let currentCategory='All',matches=[],idx=0,currentRec=null,cart=[],lang=activeLang();

function t(k){return i18n[lang][k]||k}
function categoryOrder(){return ['All',...new Set(drinks.map(d=>d.category))]}
function categoryLabel(cat){if(cat==='All')return lang==='en'?'All':'Alle';const d=drinks.find(x=>x.category===cat);return lang==='de'?(d?.category_de||cat):cat}
function applyLanguage(){
 document.documentElement.lang=lang;
 document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));
 document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));
 document.getElementById('lang').textContent=lang==='en'?'DE':'EN';
 renderFilters();renderMenu();renderCart();if(currentRec)show(currentRec,false);
}
function renderFilters(){filters.innerHTML=categoryOrder().map(c=>`<button class="${c===currentCategory?'active':''}" data-cat="${c}">${categoryLabel(c)}</button>`).join('')}
function renderMenu(){
 const q=search.value.toLowerCase().trim();
 const list=drinks.filter(d=>{
  const hay=[d.name,d.category,d.category_de,d.desc,d.desc_de,...(d.tags||[]),...(d.tags_de||[])].join(' ').toLowerCase();
  return (currentCategory==='All'||d.category===currentCategory)&&(!q||hay.includes(q))
 }).sort(bySort);
 grid.innerHTML=list.map(d=>`<article class="menu-card"><span class="cat">${lang==='de'?d.category_de:d.category}</span><span class="price">${euro(d.price)}</span><h3>${d.name}</h3><p>${lang==='de'?d.desc_de:d.desc}</p><div class="tags">${(lang==='de'?d.tags_de:d.tags).map(x=>`<span>${x}</span>`).join('')}</div><button class="card-order" data-name="${d.name}">${t('addOrder')}</button></article>`).join('');
}
function score(d,mood,tastes,strength){let s=0;if(d.moods.includes(mood))s+=7;const n=tastes.filter(x=>d.tastes.includes(x)).length;s+=n*7;if(tastes.length)s+=(n/tastes.length)*4;s+=(4-Math.abs(d.strength-strength))*1.5;if(mood==='surprise')s+=Math.random()*7;return s+Math.random()}
function recommend(){const fd=new FormData(quiz);const mood=fd.get('mood'),tastes=fd.getAll('taste'),strength=+document.getElementById('strength').value;matches=drinks.map(d=>({...d,s:score(d,mood,tastes,strength)})).sort((a,b)=>b.s-a.s).slice(0,6);idx=0;show(matches[0],true)}
function show(d,notify=true){currentRec=d;recName.textContent=d.name;recDesc.textContent=lang==='de'?d.desc_de:d.desc;recPrice.textContent=euro(d.price);match.textContent=(93+Math.floor(Math.random()*6))+'%';const vals={[t('sweetBar')]:d.tastes.includes('sweet')?88:36,[t('freshBar')]:d.tastes.includes('fresh')?91:48,[t('boldBar')]:d.strength*29,[t('curiousBar')]:d.moods.includes('adventurous')?92:58};bars.innerHTML=Object.entries(vals).map(([k,v])=>`<div class="barrow"><span>${k}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('');if(notify)toast(t('ready'))}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1400)}
function addToCart(name){const d=drinks.find(x=>x.name===name);if(!d)return;const f=cart.find(x=>x.name===name);f?f.qty++:cart.push({...d,qty:1});renderCart();toast(`${name} ${t('added')}`)}
function renderCart(){cartItems.innerHTML=cart.length?cart.map(i=>`<div class="cart-item"><span>${i.qty}× ${i.name}</span><strong>${euro(i.price*i.qty)}</strong></div>`).join(''):`<p>${t('empty')}</p>`;cartTotal.textContent=euro(cart.reduce((s,i)=>s+i.price*i.qty,0));cartCount.textContent=cart.reduce((s,i)=>s+i.qty,0)}
const tasteInputs=[...document.querySelectorAll('input[name="taste"]')];
function updateTasteLimitState(){const count=tasteInputs.filter(i=>i.checked).length;tasteInputs.forEach(i=>{const blocked=count>=3&&!i.checked;i.disabled=blocked;i.closest('label').classList.toggle('limit-blocked',blocked)})}
tasteInputs.forEach(i=>i.addEventListener('change',updateTasteLimitState));updateTasteLimitState();
quiz.addEventListener('submit',e=>{e.preventDefault();recommend()});another.addEventListener('click',()=>{idx=(idx+1)%matches.length;show(matches[idx],true)});orderBtn.addEventListener('click',()=>currentRec&&addToCart(currentRec.name));
filters.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;currentCategory=b.dataset.cat;renderFilters();renderMenu()});
search.addEventListener('input',renderMenu);grid.addEventListener('click',e=>{const b=e.target.closest('[data-name]');if(b)addToCart(b.dataset.name)});
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.go).scrollIntoView({behavior:'smooth'})));
document.querySelectorAll('[data-mood]').forEach(b=>b.addEventListener('click',()=>{const r=document.querySelector(`input[name="mood"][value="${b.dataset.mood}"]`);if(r)r.checked=true;document.getElementById('ai').scrollIntoView({behavior:'smooth'})}));
cartFab.addEventListener('click',()=>cart.classList.add('open'));closeCart.addEventListener('click',()=>cart.classList.remove('open'));
document.getElementById('lang').addEventListener('click',()=>{lang=lang==='en'?'de':'en';setActiveLang(lang);applyLanguage()});
window.addEventListener('the-sign-menu-updated',()=>{menuData=loadMenuData();drinks=menuData.drinks.filter(d=>d.visible!==false);renderFilters();renderMenu();recommend()});
applyLanguage();recommend();renderCart();
