const api=window.TheSignClubApi;let managerPin=sessionStorage.getItem('tsManagerPin')||'';let offers=[];
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(action,payload={}){return api.call(action,{managerPin,...payload})}
function showApp(){ $('#login').hidden=true;$('#app').hidden=false;loadDashboard(); }
$('#loginBtn').onclick=async()=>{managerPin=$('#pin').value.trim();try{await call('managerDashboard');sessionStorage.setItem('tsManagerPin',managerPin);showApp()}catch(e){$('#loginError').textContent=e.message}}
$('#logout').onclick=()=>{sessionStorage.removeItem('tsManagerPin');location.reload()}
document.querySelectorAll('nav button[data-view]').forEach(b=>b.onclick=()=>openView(b.dataset.view));
function openView(id){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==id);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#title').textContent=id[0].toUpperCase()+id.slice(1);if(id==='dashboard')loadDashboard();if(id==='members')loadMembers();if(id==='offers')loadOffers();if(id==='settings')loadSettings()}
async function loadDashboard(){const r=await call('managerDashboard');const d=r.dashboard;$('#dashboard').innerHTML=`<div class="stats"><div class="stat"><span>Aktive Mitglieder</span><b>${d.totalMembers}</b></div><div class="stat"><span>Neu heute</span><b>${d.newToday}</b></div><div class="stat"><span>Welcome eingelöst</span><b>${d.welcomeRedeemed}</b></div><div class="stat"><span>Visits heute</span><b>${d.visitsToday}</b></div><div class="stat"><span>Geburtstage diesen Monat</span><b>${d.birthdaysThisMonth}</b></div><div class="stat"><span>Loyalty bereit</span><b>${d.loyaltyReady}</b></div></div>`}
async function loadMembers(){const r=await call('listMembers',{query:$('#memberSearch').value});$('#memberRows').innerHTML=r.members.map(m=>`<tr><td><b>${esc(m.name)}</b><br><small>${esc(m.memberId)}</small></td><td>${esc(m.phone)}</td><td>${esc(m.email)}</td><td>${esc(m.birthday)}</td><td>${m.visits}/10</td><td>${esc(m.status)}</td></tr>`).join('')||'<tr><td colspan="6">Keine Mitglieder gefunden.</td></tr>'}
$('#memberSearchBtn').onclick=loadMembers;$('#memberSearch').addEventListener('keydown',e=>{if(e.key==='Enter')loadMembers()});
async function loadOffers(){const r=await call('listOffers');offers=r.offers;$('#offerCards').innerHTML=offers.map(o=>`<article class="offer"><span class="badge">${esc(o.type)}</span><h3>${esc(o.nameDe)}</h3><p>${esc(o.descriptionDe)}</p><div>${o.active?'Aktiv':'Inaktiv'} · ${esc(o.product||'Kein Produkt')}</div><br><button onclick="editOffer('${esc(o.offerId)}')">Bearbeiten</button></article>`).join('')}
window.editOffer=id=>{const o=offers.find(x=>x.offerId===id)||{};$('#offerId').value=o.offerId||'';$('#offerType').value=o.type||'General Promotion';$('#nameDe').value=o.nameDe||'';$('#nameEn').value=o.nameEn||'';$('#product').value=o.product||'';$('#descDe').value=o.descriptionDe||'';$('#descEn').value=o.descriptionEn||'';$('#imageUrl').value=o.imageUrl||'';$('#startDate').value=o.startDate||'';$('#endDate').value=o.endDate||'';$('#memberPrice').value=o.memberPrice??'';$('#normalPrice').value=o.normalPrice??'';$('#memberOnly').checked=o.memberOnly!==false;$('#offerActive').checked=o.active!==false;$('#offerDialog').showModal()}
$('#newOffer').onclick=()=>window.editOffer('');$('#saveOffer').onclick=async e=>{e.preventDefault();const offer={offerId:$('#offerId').value,type:$('#offerType').value,nameDe:$('#nameDe').value,nameEn:$('#nameEn').value,product:$('#product').value,descriptionDe:$('#descDe').value,descriptionEn:$('#descEn').value,imageUrl:$('#imageUrl').value,startDate:$('#startDate').value,endDate:$('#endDate').value,memberPrice:$('#memberPrice').value,normalPrice:$('#normalPrice').value,memberOnly:$('#memberOnly').checked,active:$('#offerActive').checked,maxUses:1};await call('saveOffer',{offer});$('#offerDialog').close();loadOffers()}
async function loadSettings(){const r=await call('getManagerSettings');$('#staffPin').value=r.settings.STAFF_PIN;$('#welcomeDays').value=r.settings.WELCOME_DAYS;$('#alertEmail').value=r.settings.ALERT_EMAIL||'';loadSecurityEvents()}
async function loadSecurityEvents(){try{const r=await call('listSecurityEvents');$('#securityRows').innerHTML=r.events.map(ev=>`<tr><td>${esc(new Date(ev.time).toLocaleString('de-AT'))}</td><td>${esc(ev.type)}</td><td>${esc(ev.details)}</td><td>${ev.count}</td></tr>`).join('')||'<tr><td colspan="4">Keine Ereignisse.</td></tr>'}catch(e){$('#securityRows').innerHTML=`<tr><td colspan="4">${esc(e.message)}</td></tr>`}}
$('#saveSettings').onclick=async()=>{await call('updateManagerSetting',{key:'STAFF_PIN',value:$('#staffPin').value});await call('updateManagerSetting',{key:'WELCOME_DAYS',value:$('#welcomeDays').value});await call('updateManagerSetting',{key:'ALERT_EMAIL',value:$('#alertEmail').value});const newPin=$('#newManagerPin').value.trim();if(newPin){await call('updateManagerSetting',{key:'MANAGER_PIN',value:newPin});managerPin=newPin;sessionStorage.setItem('tsManagerPin',managerPin);$('#newManagerPin').value=''}alert('Gespeichert')}
if(managerPin){showApp()}
