const STAFF_SESSION='the-sign-club-staff-session-v2';
const $=id=>document.getElementById(id);
const api=window.TheSignClubApi;
let stream=null,scanTimer=null,currentPayload=null;
function decode(s){try{s=s.replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';return JSON.parse(decodeURIComponent(escape(atob(s))))}catch{return null}}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getToken(value){try{const u=new URL(value,location.href);return u.searchParams.get('token')||u.searchParams.get('member')||value.trim()}catch{return value.trim()}}
function staffPin(){return sessionStorage.getItem(STAFF_SESSION)||''}
function resultError(message){const box=$('scanResult');box.hidden=false;box.className='club-card scan-result-card result-invalid';box.innerHTML=`<div class="scan-symbol">×</div><h2>Nicht gültig</h2><p>${esc(message)}</p>`}
async function show(value){const p=decode(getToken(value));currentPayload=p;if(!p||p.v!==3)return resultError('Dieser QR-Code gehört nicht zum aktuellen THE SIGN CLUB.');try{if(p.kind==='member')return await showMember(p);if(p.kind!=='club-offer')return resultError('Unbekannter QR-Code.');const r=await api.call('validateOffer',{staffPin:staffPin(),memberId:p.mid,offerId:p.offer});renderOffer(r.result)}catch(err){resultError(err.message==='API_NOT_CONFIGURED'?'Google-Synchronisierung ist noch nicht eingerichtet.':err.message)}}
function renderOffer(r){const box=$('scanResult'),valid=!!r.valid,m=r.member||{};box.hidden=false;box.className=`club-card scan-result-card ${valid?'result-valid':'result-invalid'}`;box.innerHTML=`<div class="scan-symbol">${valid?'✓':'×'}</div><p class="eyebrow">${esc(r.offerName||r.offerId)}</p><h2>${valid?'Gültig':'Nicht gültig'}</h2><div class="scan-person"><b>${esc(m.name)}</b><span>${esc(m.memberId)}</span><small>${esc(m.phoneDisplay||m.phone||'')}</small></div><div class="scan-facts"><div><span>Status</span><strong>${esc(r.status)}</strong></div>${r.expires?`<div><span>Gültig bis</span><strong>${new Date(r.expires).toLocaleDateString('de-AT')}</strong></div>`:''}</div>${valid?'<button id="redeemNow" class="primary full club-gold-button">Einlösung bestätigen</button>':''}${r.message&&!valid?`<p class="club-small">${esc(r.message)}</p>`:''}`;const b=$('redeemNow');if(b)b.onclick=async()=>{if(!confirm('Einlösung jetzt bestätigen?'))return;b.disabled=true;try{const x=await api.call('redeemOffer',{staffPin:staffPin(),memberId:currentPayload.mid,offerId:currentPayload.offer});renderOffer(x.result)}catch(err){resultError(err.message)}}}
async function showMember(p){try{const r=await api.call('getStaffMember',{staffPin:staffPin(),memberId:p.mid}),m=r.member;const box=$('scanResult');box.hidden=false;box.className='club-card scan-result-card result-member';box.innerHTML=`<div class="scan-symbol">◆</div><p class="eyebrow">MEMBER PASS</p><h2>${esc(m.name)}</h2><p>${esc(m.memberId)}</p><p>${esc(m.phoneDisplay||m.phone)}</p><div class="visits-box"><span>Bestätigte Drinks</span><strong>${m.visits||0} / 10</strong><div><i style="width:${Math.min(m.visits||0,10)*10}%"></i></div></div><button id="addVisit" class="primary full club-gold-button">+ 1 Drink bestätigen</button><p class="club-small">Nur nach einem tatsächlich bezahlten Drink bestätigen.</p>`;$('addVisit').onclick=async()=>{if(!confirm('Einen bestätigten Drink hinzufügen?'))return;try{await api.call('addVisit',{staffPin:staffPin(),memberId:p.mid});showMember(p)}catch(err){resultError(err.message)}}}catch(err){resultError(err.message)}}
function openScanner(){if(!api.configured())return resultError('Bitte zuerst die Google Apps Script /exec URL in club-api.js eintragen.');$('staffLogin').hidden=true;$('scannerArea').hidden=false;const initial=new URLSearchParams(location.search).get('token')||new URLSearchParams(location.search).get('member');if(initial){$('tokenInput').value=initial;show(initial)}}
$('staffLoginBtn').onclick=async()=>{const pin=$('staffPin').value.trim();if(!pin){$('staffLoginError').hidden=false;return}const btn=$('staffLoginBtn');btn.disabled=true;$('staffLoginError').hidden=true;try{await api.call('verifyStaff',{staffPin:pin});sessionStorage.setItem(STAFF_SESSION,pin);openScanner()}catch(err){sessionStorage.removeItem(STAFF_SESSION);$('staffLoginError').textContent=err.message==='API_NOT_CONFIGURED'?'Google API ist noch nicht verbunden.':'Falscher PIN oder keine Verbindung.';$('staffLoginError').hidden=false}finally{btn.disabled=false}};$('staffPin').addEventListener('keydown',e=>{if(e.key==='Enter')$('staffLoginBtn').click()});if(sessionStorage.getItem(STAFF_SESSION)){api.call('verifyStaff',{staffPin:staffPin()}).then(openScanner).catch(()=>sessionStorage.removeItem(STAFF_SESSION));}
$('checkToken').onclick=()=>show($('tokenInput').value);
$('startScan').onclick=async()=>{if(!('BarcodeDetector'in window)){alert('Dieser Browser unterstützt den eingebauten Scanner nicht. Bitte die normale Handykamera verwenden und den QR-Code öffnen.');return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const v=$('scanVideo');v.srcObject=stream;v.hidden=false;await v.play();const detector=new BarcodeDetector({formats:['qr_code']});scanTimer=setInterval(async()=>{try{const codes=await detector.detect(v);if(codes[0]){clearInterval(scanTimer);stream.getTracks().forEach(t=>t.stop());v.hidden=true;const raw=codes[0].rawValue;$('tokenInput').value=raw;show(raw)}}catch{}},350)}catch{alert('Kamera konnte nicht geöffnet werden. Kamera-Berechtigung und HTTPS prüfen.')}};
