const MEMBER_CACHE='the-sign-club-cloud-member-v1';
const SESSION_TOKEN='the-sign-club-cloud-token-v1';
let clubLang=localStorage.getItem('the-sign-club-lang')||'de';
let memberCache=null;
const $=id=>document.getElementById(id);
const api=window.TheSignClubApi || {configured:()=>false,call:async()=>{const e=new Error('API_NOT_CONFIGURED');e.code='API_NOT_CONFIGURED';throw e;}};
const copy={
 de:{title:'Deine Vorteile. Einfach und exklusiv.',lead:'Registrieren, Vorteil erhalten und beim nächsten Besuch einlösen.',reg:'Kostenlos registrieren',loginTitle:'Mitglied anmelden',registerTab:'Registrieren',loginTab:'Anmelden',name:'Vorname',phone:'Telefonnummer',phoneHint:'Eine Telefonnummer kann nur einmal registriert werden.',email:'E-Mail',password:'Passwort',passwordHint:'Mindestens 6 Zeichen',birthday:'Geburtsdatum',birthdayHint:'Das Geburtsjahr wird nicht benötigt.',privacy:'Ich akzeptiere die <a href="datenschutz-club.html" target="_blank">Datenschutzerklärung</a>.',marketing:'Ich möchte Angebote, Neuigkeiten und Veranstaltungen per E-Mail erhalten.',join:'Jetzt Mitglied werden',login:'Anmelden',notice:'Marketing-Mitteilungen sind freiwillig und jederzeit abbestellbar.',hello:'Hallo',newOffers:'Deine Club Vorteile',offers:'Angebote',benefits:'Meine Vorteile',active:'Aktive Vorteile',all:'Alle Angebote',showQr:'Mitglieds-QR anzeigen',myData:'Meine Daten & Einstellungen',phoneData:'Telefonnummer',emailData:'E-Mail',birthdayData:'Geburtstag',marketingToggle:'Angebote, Neuigkeiten und Veranstaltungen per E-Mail erhalten.',saved:'Gespeichert.',privacyLink:'Datenschutz',logout:'Abmelden',delete:'Anmeldung auf diesem Gerät entfernen',available:'Verfügbar',redeemed:'Eingelöst',expired:'Abgelaufen',soon:'Bald verfügbar',validUntil:'Gültig bis',details:'Details anzeigen',showCoupon:'QR-Code anzeigen',staffOnly:'Die Einlösung wird ausschließlich vom Personal bestätigt.',welcomeTitle:'Willkommen im THE SIGN CLUB',welcomeText:'Dein Welcome Drink ist jetzt verfügbar.',loyalty:'LOYALTY',remaining:n=>`Noch ${n} bis zum Reward`,loyaltyInfo:'Nach 10 bestätigten Drinks wird automatisch ein Reward freigeschaltet.',duplicatePhone:'Diese Telefonnummer ist bereits registriert. Bitte melde dich an.',duplicateEmail:'Diese E-Mail ist bereits registriert.',invalid:'Bitte alle Pflichtfelder korrekt ausfüllen.',loginInvalid:'Telefonnummer oder Passwort ist nicht korrekt.',offline:'Google-Synchronisierung ist noch nicht eingerichtet oder momentan nicht erreichbar.',confirmDelete:'Nur die Anmeldung auf diesem Gerät entfernen? Das zentrale Mitgliedskonto bleibt bestehen.',qrHint:'Beim Personal vorzeigen.',offersData:{welcome:['WELCOME DRINK','Ein kostenloses ausgewähltes Getränk für neue Mitglieder.'],birthday:['BIRTHDAY DRINK','Dein Geburtstagsdrink wartet in deinem Geburtstagsmonat auf dich.'],monthly:['COCKTAIL OF THE MONTH','Espresso Martini zum exklusiven Member-Preis von €8,90.'],loyalty:['LOYALTY REWARD','10 bestätigte Drinks öffnen deinen nächsten Club Reward.']}},
 en:{title:'Your benefits. Simple and exclusive.',lead:'Register, receive your benefit and redeem it on your next visit.',reg:'Register for free',loginTitle:'Member login',registerTab:'Register',loginTab:'Log in',name:'First name',phone:'Phone number',phoneHint:'A phone number can only be registered once.',email:'Email',password:'Password',passwordHint:'At least 6 characters',birthday:'Date of birth',birthdayHint:'Your birth year is not required.',privacy:'I accept the <a href="datenschutz-club.html" target="_blank">privacy policy</a>.',marketing:'I want to receive offers, news and events by email.',join:'Join the club',login:'Log in',notice:'Marketing messages are optional and can be unsubscribed at any time.',hello:'Hello',newOffers:'Your Club benefits',offers:'Offers',benefits:'My benefits',active:'Active benefits',all:'All offers',showQr:'Show member QR',myData:'My data & settings',phoneData:'Phone number',emailData:'Email',birthdayData:'Birthday',marketingToggle:'Receive offers, news and events by email.',saved:'Saved.',privacyLink:'Privacy',logout:'Log out',delete:'Remove login from this device',available:'Available',redeemed:'Redeemed',expired:'Expired',soon:'Coming soon',validUntil:'Valid until',details:'View details',showCoupon:'Show QR code',staffOnly:'Redemption can only be confirmed by staff.',welcomeTitle:'Welcome to THE SIGN CLUB',welcomeText:'Your Welcome Drink is now available.',loyalty:'LOYALTY',remaining:n=>`${n} more until your reward`,loyaltyInfo:'After 10 confirmed drinks, a reward is unlocked automatically.',duplicatePhone:'This phone number is already registered. Please log in.',duplicateEmail:'This email is already registered.',invalid:'Please complete all required fields correctly.',loginInvalid:'The phone number or password is incorrect.',offline:'Google synchronization is not configured or currently unavailable.',confirmDelete:'Remove only the login from this device? The central member account remains active.',qrHint:'Show this to staff.',offersData:{welcome:['WELCOME DRINK','A complimentary selected drink for new members.'],birthday:['BIRTHDAY DRINK','Your birthday drink awaits during your birthday month.'],monthly:['COCKTAIL OF THE MONTH','Espresso Martini at the exclusive member price of €8.90.'],loyalty:['LOYALTY REWARD','10 confirmed drinks unlock your next Club Reward.']}}
};
for(let i=1;i<=31;i++)$('birthDay').insertAdjacentHTML('beforeend',`<option value="${i}">${i}</option>`);
for(let i=1;i<=12;i++)$('birthMonth').insertAdjacentHTML('beforeend',`<option value="${i}">${i}</option>`);
function token(){return localStorage.getItem(SESSION_TOKEN)||''}
function cacheMember(m){memberCache=m;localStorage.setItem(MEMBER_CACHE,JSON.stringify(m))}
function currentMember(){if(memberCache)return memberCache;try{return JSON.parse(localStorage.getItem(MEMBER_CACHE))}catch{return null}}
function clearLogin(){memberCache=null;localStorage.removeItem(MEMBER_CACHE);localStorage.removeItem(SESSION_TOKEN)}
function tokenEncode(obj){return btoa(unescape(encodeURIComponent(JSON.stringify(obj)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function fmt(date){return new Date(date).toLocaleDateString(clubLang==='de'?'de-AT':'en-GB')}
function statusFor(type,m){const now=new Date();if(type==='welcome'){if(m.welcomeRedeemedAt||m.rewards?.welcome?.status==='REDEEMED')return'redeemed';if(now>new Date(m.welcomeExpires))return'expired';return'available'}if(type==='birthday')return Number(m.birthMonth)===now.getMonth()+1?'available':'soon';if(type==='monthly')return'available';if(type==='loyalty')return m.rewards?.loyalty?.status==='AVAILABLE'||(m.visits||0)>=10?'available':'soon';return'soon'}
function offerList(m){return[{id:'welcome',type:'Welcome',image:'lounge.jpg',valid:m.welcomeExpires,drink:clubLang==='de'?'Ausgewählte Welcome Drinks':'Selected welcome drinks'},{id:'birthday',type:'Birthday',image:'lounge.jpg',valid:clubLang==='de'?'Im Geburtstagsmonat':'During birthday month',drink:clubLang==='de'?'Ein ausgewählter Drink':'One selected drink'},{id:'monthly',type:'Monthly Deal',image:'lounge.jpg',valid:clubLang==='de'?'Diesen Monat':'This month',drink:'Espresso Martini · €8.90'},{id:'loyalty',type:'Loyalty Reward',image:'lounge.jpg',valid:`${m.visits||0} / 10 Drinks`,drink:clubLang==='de'?'Ausgewählter Reward Drink':'Selected reward drink'}]}
function switchAuth(mode){const login=mode==='login';$('clubForm').hidden=login;$('loginForm').hidden=!login;$('showRegister').classList.toggle('active',!login);$('showLogin').classList.toggle('active',login);$('registerTitle').textContent=login?copy[clubLang].loginTitle:copy[clubLang].reg;$('formError').hidden=true;$('loginError').hidden=true}
function applyLang(){const t=copy[clubLang];[['clubTitle','title'],['clubLead','lead'],['showRegister','registerTab'],['showLogin','loginTab'],['nameLabel','name'],['phoneLabel','phone'],['phoneHint','phoneHint'],['emailLabel','email'],['passwordLabel','password'],['passwordHint','passwordHint'],['birthdayLabel','birthday'],['birthdayHint','birthdayHint'],['marketingText','marketing'],['joinBtn','join'],['clubNotice','notice'],['loginPhoneLabel','phone'],['loginPasswordLabel','password'],['loginBtn','login'],['helloText','hello'],['newOffersText','newOffers'],['offersTab','offers'],['benefitsTab','benefits'],['activeOffersTitle','active'],['showAllOffers','all'],['showQrText','showQr'],['benefitsTitle','benefits'],['loyaltyPanelLabel','loyalty'],['loyaltyInfo','loyaltyInfo'],['myDataTitle','myData'],['dataPhoneLabel','phoneData'],['dataEmailLabel','emailData'],['dataBirthdayLabel','birthdayData'],['marketingToggleText','marketingToggle'],['marketingSaved','saved'],['privacyLink','privacyLink'],['logoutMember','logout'],['deleteMember','delete'],['welcomeFlashTitle','welcomeTitle'],['welcomeFlashText','welcomeText'],['memberQrHint','qrHint']].forEach(([id,k])=>$(id).textContent=t[k]);$('privacyText').innerHTML=t.privacy;const m=currentMember();if(m)renderMember(m)}
function renderOffers(m){const t=copy[clubLang];$('offerGrid').innerHTML=offerList(m).map(o=>{const s=statusFor(o.id,m),data=t.offersData[o.id];return `<article class="offer-card offer-${o.id}"><div class="offer-image" style="background-image:linear-gradient(180deg,transparent,rgba(0,0,0,.82)),url('${o.image}')"><span class="offer-type">${o.type}</span><span class="offer-status status-${s}">${t[s]}</span></div><div class="offer-body"><h3>${data[0]}</h3><p>${data[1]}</p><div class="offer-meta"><span>${t.validUntil}</span><strong>${String(o.valid).includes('T')?fmt(o.valid):o.valid}</strong></div><div class="offer-meta"><span>${clubLang==='de'?'Vorteil':'Benefit'}</span><strong>${o.drink}</strong></div><button class="offer-action" data-offer="${o.id}">${s==='available'?t.showCoupon:t.details}</button></div></article>`}).join('');document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>openOffer(b.dataset.offer,m))}
function couponUrl(o,m){const payload={v:3,kind:'club-offer',offer:o.id,mid:m.memberId};const u=new URL('member-admin.html',location.href);u.searchParams.set('token',tokenEncode(payload));return u.href}
function openOffer(id,m){const o=offerList(m).find(x=>x.id===id),s=statusFor(id,m),d=copy[clubLang].offersData[id],t=copy[clubLang],canQr=s==='available';$('offerModalContent').innerHTML=`<div class="modal-offer-image" style="background-image:linear-gradient(180deg,transparent,rgba(0,0,0,.88)),url('${o.image}')"><span class="offer-status status-${s}">${t[s]}</span><h2>${d[0]}</h2></div><p>${d[1]}</p><div class="offer-detail-list"><div><span>${t.validUntil}</span><b>${String(o.valid).includes('T')?fmt(o.valid):o.valid}</b></div><div><span>${clubLang==='de'?'Auswahl':'Selection'}</span><b>${o.drink}</b></div></div>${canQr?'<div id="couponQr" class="member-qr coupon-qr"></div><p class="club-small">'+t.staffOnly+'</p>':'<p class="club-status-message">'+t[s]+'</p>'}`;$('offerModal').hidden=false;document.body.classList.add('modal-open');if(canQr&&window.QRCode)new QRCode($('couponQr'),{text:couponUrl(o,m),width:220,height:220,correctLevel:QRCode.CorrectLevel.M})}
function renderMember(m){cacheMember(m);$('guestHero').hidden=true;$('registerCard').hidden=true;$('memberArea').hidden=false;$('memberDisplayName').textContent=m.name;$('memberId').textContent=m.memberId;$('memberPhoneDisplay').textContent=m.phoneDisplay||m.phone;$('memberEmailDisplay').textContent=m.email;$('memberBirthdayDisplay').textContent=`${String(m.birthDay).padStart(2,'0')}.${String(m.birthMonth).padStart(2,'0')}.`;$('marketingToggle').checked=!!m.marketingConsent;const visits=m.visits||0;$('visitsValue').textContent=`${visits} / 10 Drinks`;$('loyaltyBar').style.width=`${Math.min(visits,10)*10}%`;$('loyaltyRemaining').textContent=copy[clubLang].remaining(Math.max(0,10-visits));renderOffers(m)}
function showGuest(login=false){$('guestHero').hidden=false;$('registerCard').hidden=false;$('memberArea').hidden=true;switchAuth(login?'login':'register');window.scrollTo({top:0,behavior:'smooth'})}
function showError(el,err){const t=copy[clubLang];el.textContent=err.code==='PHONE_EXISTS'?t.duplicatePhone:err.code==='EMAIL_EXISTS'?t.duplicateEmail:err.code==='LOGIN_INVALID'?t.loginInvalid:err.message==='API_NOT_CONFIGURED'?t.offline:(err.message||t.offline);el.hidden=false}
async function syncMember(){if(!token()||!api.configured())return;try{const r=await api.call('getMember',{token:token()});renderMember(r.member)}catch(err){if(err.code==='SESSION_INVALID'){clearLogin();showGuest(true)}}}
$('clubForm').addEventListener('submit',async e=>{e.preventDefault();$('formError').hidden=true;if(!e.currentTarget.checkValidity())return showError($('formError'),new Error(copy[clubLang].invalid));const button=$('joinBtn');button.disabled=true;try{const r=await api.call('register',{name:$('memberName').value.trim(),phone:$('memberPhone').value.trim(),phoneDisplay:$('memberPhone').value.trim(),email:$('memberEmail').value.trim().toLowerCase(),password:$('memberPassword').value,birthDay:Number($('birthDay').value),birthMonth:Number($('birthMonth').value),privacyConsent:$('privacyConsent').checked,marketingConsent:$('marketingConsent').checked});localStorage.setItem(SESSION_TOKEN,r.token);renderMember(r.member);$('welcomeFlash').hidden=false;setTimeout(()=>$('welcomeFlash').hidden=true,7000);window.scrollTo({top:0,behavior:'smooth'})}catch(err){showError($('formError'),err);if(err.code==='PHONE_EXISTS'){setTimeout(()=>switchAuth('login'),900)}}finally{button.disabled=false}});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').hidden=true;const button=$('loginBtn');button.disabled=true;try{const r=await api.call('login',{phone:$('loginPhone').value.trim(),password:$('loginPassword').value});localStorage.setItem(SESSION_TOKEN,r.token);renderMember(r.member);window.scrollTo({top:0,behavior:'smooth'})}catch(err){showError($('loginError'),err)}finally{button.disabled=false}});
$('showRegister').onclick=()=>switchAuth('register');$('showLogin').onclick=()=>switchAuth('login');$('clubLang').onclick=()=>{clubLang=clubLang==='de'?'en':'de';localStorage.setItem('the-sign-club-lang',clubLang);applyLang()};
document.querySelectorAll('[data-club-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-club-tab]').forEach(x=>x.classList.toggle('active',x===b));$('offersView').hidden=b.dataset.clubTab!=='offers';$('benefitsView').hidden=b.dataset.clubTab!=='benefits'});
$('closeOfferModal').onclick=()=>{$('offerModal').hidden=true;document.body.classList.remove('modal-open')};
$('showMemberQr').onclick=()=>{const m=currentMember();if(!m)return;$('memberQrName').textContent=m.name;$('memberQrId').textContent=m.memberId;$('memberQr').innerHTML='';const u=new URL('member-admin.html',location.href);u.searchParams.set('member',tokenEncode({v:3,kind:'member',mid:m.memberId}));if(window.QRCode)new QRCode($('memberQr'),{text:u.href,width:220,height:220,correctLevel:QRCode.CorrectLevel.M});$('memberQrModal').hidden=false;document.body.classList.add('modal-open')};
$('closeMemberQr').onclick=()=>{$('memberQrModal').hidden=true;document.body.classList.remove('modal-open')};
$('marketingToggle').onchange=async()=>{try{const r=await api.call('updateMarketing',{token:token(),marketingConsent:$('marketingToggle').checked});renderMember(r.member);$('marketingSaved').hidden=false;setTimeout(()=>$('marketingSaved').hidden=true,1800)}catch(err){$('marketingToggle').checked=!$('marketingToggle').checked;alert(err.message)}};
$('logoutMember').onclick=()=>{clearLogin();showGuest(true)};
$('deleteMember').onclick=()=>{if(confirm(copy[clubLang].confirmDelete)){clearLogin();showGuest(false)}};
applyLang();const cached=currentMember();if(cached)renderMember(cached);else showGuest(false);syncMember();window.addEventListener('focus',syncMember);document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncMember()});
