window.V11_CATALOG = [
  {
    "id": "drink-vienna-tradition",
    "name": "Vienna Tradition",
    "category": "Spritz",
    "category_de": "Spritz",
    "sort": 10,
    "price": 25,
    "volume": "0,75 l",
    "desc": "Bottle of Poeschel Riesling with Römerquelle soda water.",
    "desc_de": "Flasche Poeschel Riesling mit Römerquelle Sodawasser.",
    "image": "images/drinks/vienna-tradition.jpg"
  },
  {
    "id": "drink-super-cattivo-aperol",
    "name": "Super Cattivo ‘Aperol’ Spritz",
    "category": "Spritz",
    "category_de": "Spritz",
    "sort": 20,
    "price": 11,
    "desc": "Aperol-style spritz with Prosecco and soda.",
    "desc_de": "Aperol Spritz mit Prosecco und Soda.",
    "image": "images/drinks/super-cattivo-aperol-spritz.jpg"
  },
  {
    "id": "drink-super-cattivo-campari",
    "name": "Super Cattivo ‘Campari’ Spritz",
    "category": "Spritz",
    "category_de": "Spritz",
    "sort": 30,
    "price": 11,
    "desc": "Campari-style spritz with orange and soda.",
    "desc_de": "Campari Spritz mit Orange und Soda.",
    "image": "images/drinks/super-cattivo-campari-spritz.jpg"
  },
  {
    "id": "drink-super-cattivo-bergamot",
    "name": "Super Cattivo ‘Bergamot’ Spritz",
    "category": "Spritz",
    "category_de": "Spritz",
    "sort": 40,
    "price": 11,
    "desc": "Bergamot spritz with Prosecco and soda.",
    "desc_de": "Bergamotte Spritz mit Prosecco und Soda.",
    "image": "images/drinks/super-cattivo-bergamot-spritz.jpg"
  },
  {
    "id": "drink-basil-limoncello",
    "name": "Basil Limoncello Spritz",
    "category": "Spritz",
    "category_de": "Spritz",
    "sort": 50,
    "price": 11,
    "desc": "Homemade basil limoncello, Prosecco and soda.",
    "desc_de": "Hausgemachter Basilikum-Limoncello, Prosecco und Soda.",
    "image": "images/drinks/basil-limoncello-spritz.jpg"
  },
  {
    "id": "drink-poeschl-riesling",
    "name": "Poeschel Riesling",
    "category": "Wine",
    "category_de": "Wein",
    "sort": 60,
    "price": 28,
    "desc": "White wine.",
    "desc_de": "Weißwein.",
    "image": "images/drinks/poeschel-riesling.jpg"
  },
  {
    "id": "drink-poeschl-blauburger",
    "name": "Poeschel Blauburger",
    "category": "Wine",
    "category_de": "Wein",
    "sort": 70,
    "price": 31,
    "desc": "Red wine.",
    "desc_de": "Rotwein.",
    "image": "images/drinks/poeschel-blauburger.jpg"
  },
  {
    "id": "drink-ortus-roter-veltliner",
    "name": "Ortus Roter Veltliner",
    "category": "Wine",
    "category_de": "Wein",
    "sort": 80,
    "price": 39,
    "desc": "Austrian white wine.",
    "desc_de": "Österreichischer Weißwein.",
    "image": "images/drinks/ortus-roter-veltliner.jpg"
  },
  {
    "id": "drink-casa-gherler",
    "name": "Casa Gheller Bianco Frizzante",
    "category": "Bubbles",
    "category_de": "Schaumwein",
    "sort": 90,
    "price": 6.5,
    "volume": "0,1 l",
    "desc": "Bianco Frizzante by the glass.",
    "desc_de": "Bianco Frizzante im Glas.",
    "image": "images/drinks/casa-gheller-bianco-frizzante.jpg"
  },
  {
    "id": "drink-gratien-meyer",
    "name": "Gratien & Meyer Crémant de Loire Brut",
    "category": "Bubbles",
    "category_de": "Schaumwein",
    "sort": 100,
    "price": 42,
    "volume": "0,75 l",
    "desc": "Crémant de Loire Brut.",
    "desc_de": "Crémant de Loire Brut.",
    "image": "images/drinks/gratien-meyer-cremant.jpg"
  },
  {
    "id": "drink-chandon-garden",
    "name": "Chandon Garden Spritz",
    "category": "Bubbles",
    "category_de": "Schaumwein",
    "sort": 110,
    "price": 65,
    "desc": "Chandon Garden Spritz bottle.",
    "desc_de": "Chandon Garden Spritz Flasche.",
    "image": "images/drinks/chandon-garden-spritz.jpg"
  },
  {
    "id": "drink-canard-duchene",
    "name": "Canard Duchêne Léonie Brut",
    "category": "Champagne",
    "category_de": "Champagner",
    "sort": 120,
    "price": 95,
    "desc": "Champagne Brut.",
    "desc_de": "Champagner Brut.",
    "image": "images/drinks/canard-duchene-leonie-brut.jpg"
  },
  {
    "id": "drink-moet-imperial",
    "name": "Moët & Chandon Brut Impérial",
    "category": "Champagne",
    "category_de": "Champagner",
    "sort": 130,
    "price": 119,
    "desc": "Champagne Brut Impérial.",
    "desc_de": "Champagner Brut Impérial.",
    "image": "images/drinks/moet-chandon-brut-imperial.jpg"
  },
  {
    "id": "drink-moet-rose",
    "name": "Moët & Chandon Impérial Rosé",
    "category": "Champagne",
    "category_de": "Champagner",
    "sort": 140,
    "price": 149,
    "desc": "Champagne Impérial Rosé.",
    "desc_de": "Champagner Impérial Rosé.",
    "image": "images/drinks/moet-chandon-imperial-rose.jpg"
  },
  {
    "id": "drink-veuve",
    "name": "Veuve Clicquot Brut",
    "category": "Champagne",
    "category_de": "Champagner",
    "sort": 150,
    "price": 129,
    "desc": "Champagne Brut.",
    "desc_de": "Champagner Brut.",
    "image": "images/drinks/veuve-clicquot-brut.jpg"
  },
  {
    "id": "drink-villacher",
    "name": "Draft Villacher Pils",
    "category": "Beer",
    "category_de": "Bier",
    "sort": 160,
    "price": 4.5,
    "volume": "0,3 l",
    "desc": "Draft lager.",
    "desc_de": "Villacher Pils vom Fass.",
    "image": "images/drinks/draft-villacher-pils.jpg"
  },
  {
    "id": "drink-villacher-07",
    "name": "Draft Villacher Pils",
    "category": "Beer",
    "category_de": "Bier",
    "sort": 170,
    "price": 5.9,
    "volume": "0,7 l",
    "desc": "Large draft lager.",
    "desc_de": "Großes Villacher Pils vom Fass.",
    "image": "images/drinks/draft-villacher-pils-07.jpg"
  },
  {
    "id": "drink-budweiser",
    "name": "Budweiser",
    "category": "Beer",
    "category_de": "Bier",
    "sort": 180,
    "price": 5.2,
    "volume": "0,33 l",
    "desc": "Bottled beer.",
    "desc_de": "Flaschenbier.",
    "image": "images/drinks/budweiser.jpg"
  },
  {
    "id": "drink-edelweiss",
    "name": "Edelweiss Wheat Beer",
    "category": "Beer",
    "category_de": "Bier",
    "sort": 190,
    "price": 6.5,
    "volume": "0,5 l",
    "desc": "Wheat beer.",
    "desc_de": "Weißbier.",
    "image": "images/drinks/edelweiss-wheat-beer.jpg"
  },
  {
    "id": "drink-corona",
    "name": "Corona Beer",
    "category": "Beer",
    "category_de": "Bier",
    "sort": 200,
    "price": 6,
    "volume": "0,33 l",
    "desc": "Bottled lager.",
    "desc_de": "Flaschenbier.",
    "image": "images/drinks/corona-beer.jpg"
  },
  {
    "id": "drink-roemer-still",
    "name": "Römerquelle Still",
    "category": "Water",
    "category_de": "Wasser",
    "sort": 210,
    "price": 5.9,
    "volume": "0,7 l",
    "desc": "Still mineral water.",
    "desc_de": "Stilles Mineralwasser.",
    "image": "images/drinks/roemerquelle-still.jpg"
  },
  {
    "id": "drink-roemer-sparkling",
    "name": "Römerquelle Sparkling",
    "category": "Water",
    "category_de": "Wasser",
    "sort": 220,
    "price": 5.9,
    "volume": "0,7 l",
    "desc": "Sparkling mineral water.",
    "desc_de": "Mineralwasser mit Kohlensäure.",
    "image": "images/drinks/roemerquelle-sparkling.jpg"
  },
  {
    "id": "drink-tap-water",
    "name": "Leitungswasser",
    "category": "Soft Drinks",
    "category_de": "Alkoholfreie Getränke",
    "sort": 230,
    "price": 1,
    "volume": "0,5 l",
    "desc": "Tap water.",
    "desc_de": "Leitungswasser.",
    "image": "images/drinks/leitungswasser.jpg"
  },
  {
    "id": "drink-soda-025",
    "name": "Soda Wasser",
    "category": "Soft Drinks",
    "category_de": "Alkoholfreie Getränke",
    "sort": 240,
    "price": 3.2,
    "volume": "0,25 l",
    "desc": "Soda water.",
    "desc_de": "Sodawasser.",
    "image": "images/drinks/soda-wasser-025.jpg"
  },
  {
    "id": "drink-soda-05",
    "name": "Soda Wasser",
    "category": "Soft Drinks",
    "category_de": "Alkoholfreie Getränke",
    "sort": 250,
    "price": 5.6,
    "volume": "0,5 l",
    "desc": "Soda water.",
    "desc_de": "Sodawasser.",
    "image": "images/drinks/soda-wasser-05.jpg"
  },
  {
    "id": "drink-soda-lemon-025",
    "name": "Soda Zitrone",
    "category": "Soft Drinks",
    "category_de": "Alkoholfreie Getränke",
    "sort": 260,
    "price": 3.5,
    "volume": "0,25 l",
    "desc": "Soda with lemon.",
    "desc_de": "Soda mit Zitrone.",
    "image": "images/drinks/soda-zitrone-025.jpg"
  },
  {
    "id": "drink-soda-lemon-05",
    "name": "Soda Zitrone",
    "category": "Soft Drinks",
    "category_de": "Alkoholfreie Getränke",
    "sort": 270,
    "price": 5.9,
    "volume": "0,5 l",
    "desc": "Soda with lemon.",
    "desc_de": "Soda mit Zitrone.",
    "image": "images/drinks/soda-zitrone-05.jpg"
  },
  {
    "id": "drink-coca-cola",
    "name": "Coca-Cola",
    "category": "Soft Drinks",
    "category_de": "Alkoholfreie Getränke",
    "sort": 280,
    "price": 4.5,
    "volume": "0,33 l",
    "desc": "Coca-Cola.",
    "desc_de": "Coca-Cola.",
    "image": "images/drinks/coca-cola.jpg"
  },
  {
    "id": "drink-coca-cola-light",
    "name": "Coca-Cola Light",
    "category": "Soft Drinks",
    "category_de": "Alkoholfreie Getränke",
    "sort": 290,
    "price": 4.5,
    "volume": "0,33 l",
    "desc": "Coca-Cola Light.",
    "desc_de": "Coca-Cola Light.",
    "image": "images/drinks/coca-cola-light.jpg"
  },
  {
    "id": "drink-fever-tree",
    "name": "Fever-Tree Tonic Water",
    "category": "Soft Drinks",
    "category_de": "Alkoholfreie Getränke",
    "sort": 300,
    "price": 4.9,
    "volume": "0,2 l",
    "desc": "Premium tonic water.",
    "desc_de": "Premium Tonic Water.",
    "image": "images/drinks/fever-tree-tonic-water.jpg"
  },
  {
    "id": "drink-schweppes",
    "name": "Schweppes Tonic Water",
    "category": "Soft Drinks",
    "category_de": "Alkoholfreie Getränke",
    "sort": 310,
    "price": 4.5,
    "volume": "0,2 l",
    "desc": "Tonic water.",
    "desc_de": "Tonic Water.",
    "image": "images/drinks/schweppes-tonic-water.jpg"
  },
  {
    "id": "food-spring-rolls",
    "name": "Chinese Spring Rolls",
    "category": "Kitchen",
    "category_de": "Küche",
    "sort": 320,
    "price": 7.5,
    "desc": "With cabbage, glass noodles and wood ear mushrooms. Served with sweet chilli sauce.",
    "desc_de": "Mit Kohl, Glasnudeln und Mu-Err-Pilzen. Serviert mit Sweet-Chili-Sauce.",
    "allergens": "A N F",
    "image": "images/food/chinese-spring-rolls.jpg"
  },
  {
    "id": "food-dumplings",
    "name": "Homemade Dumplings",
    "category": "Kitchen",
    "category_de": "Küche",
    "sort": 330,
    "price": 7.9,
    "desc": "With cabbage and pork. Served with soy sauce or sweet chilli sauce.",
    "desc_de": "Mit Kohl und Schweinefleisch. Serviert mit Sojasauce oder Sweet-Chili-Sauce.",
    "allergens": "A N F",
    "image": "images/food/homemade-dumplings.jpg"
  },
  {
    "id": "food-karaage",
    "name": "Japanese Karaage Chicken",
    "category": "Kitchen",
    "category_de": "Küche",
    "sort": 340,
    "price": 7.9,
    "desc": "Served with yuzu spicy mayo.",
    "desc_de": "Serviert mit würziger Yuzu-Mayonnaise.",
    "allergens": "A C M",
    "image": "images/food/japanese-karaage-chicken.jpg"
  },
  {
    "id": "food-tempura",
    "name": "Tempura Shrimp",
    "category": "Kitchen",
    "category_de": "Küche",
    "sort": 350,
    "price": 7.5,
    "desc": "Served with yuzu spicy mayo.",
    "desc_de": "Serviert mit würziger Yuzu-Mayonnaise.",
    "allergens": "A B C M",
    "image": "images/food/tempura-shrimp.jpg"
  },
  {
    "id": "food-fries",
    "name": "Fries",
    "category": "Kitchen",
    "category_de": "Küche",
    "sort": 360,
    "price": 5.9,
    "desc": "Served with mayo and ketchup.",
    "desc_de": "Serviert mit Mayonnaise und Ketchup.",
    "allergens": "C M",
    "image": "images/food/fries.jpg"
  },
  {
    "id": "food-hotdog",
    "name": "Korean Hot Dog",
    "category": "Kitchen",
    "category_de": "Küche",
    "sort": 370,
    "price": 4.5,
    "desc": "Served with mayo and ketchup.",
    "desc_de": "Serviert mit Mayonnaise und Ketchup.",
    "allergens": "A C M",
    "image": "images/food/korean-hot-dog.jpg"
  },
  {
    "id": "food-chips",
    "name": "Salted Potato Chips",
    "category": "Kitchen",
    "category_de": "Küche",
    "sort": 380,
    "price": 2.5,
    "desc": "Salted potato chips.",
    "desc_de": "Gesalzene Kartoffelchips.",
    "allergens": "A",
    "image": "images/food/salted-potato-chips.jpg"
  },
  {
    "id": "food-popcorn",
    "name": "Classic Salted Popcorn",
    "category": "Kitchen",
    "category_de": "Küche",
    "sort": 390,
    "price": 4.9,
    "desc": "Classic salted popcorn.",
    "desc_de": "Klassisches gesalzenes Popcorn.",
    "allergens": "–",
    "image": "images/food/classic-salted-popcorn.jpg"
  },
  {
    "id": "food-mala-popcorn",
    "name": "Sichuan Mala Spicy Popcorn",
    "category": "Kitchen",
    "category_de": "Küche",
    "sort": 400,
    "price": 5.9,
    "desc": "Corn, Sichuan pepper, chilli and spices.",
    "desc_de": "Mais, Sichuanpfeffer, Chili und Gewürze.",
    "allergens": "A",
    "image": "images/food/sichuan-mala-spicy-popcorn.jpg"
  },
  {
    "id": "dessert-matcha",
    "name": "Matcha Ice Cream Mochi",
    "category": "Dessert",
    "category_de": "Dessert",
    "sort": 410,
    "price": 2.2,
    "volume": "1 piece",
    "desc": "Delicate Japanese rice cake with matcha ice cream filling.",
    "desc_de": "Japanischer Reiskuchen mit Matcha-Eisfüllung.",
    "allergens": "Ask staff",
    "image": "images/desserts/matcha-ice-cream-mochi.jpg"
  },
  {
    "id": "dessert-strawberry",
    "name": "Strawberry Ice Cream Mochi",
    "category": "Dessert",
    "category_de": "Dessert",
    "sort": 420,
    "price": 2.2,
    "volume": "1 piece",
    "desc": "Delicate Japanese rice cake with strawberry ice cream filling.",
    "desc_de": "Japanischer Reiskuchen mit Erdbeer-Eisfüllung.",
    "allergens": "Ask staff",
    "image": "images/desserts/strawberry-ice-cream-mochi.jpg"
  },
  {
    "id": "dessert-redbean",
    "name": "Red Bean Mochi",
    "category": "Dessert",
    "category_de": "Dessert",
    "sort": 430,
    "price": 2.2,
    "volume": "1 piece",
    "desc": "Delicate Japanese rice cake with red bean filling.",
    "desc_de": "Japanischer Reiskuchen mit roter Bohnenfüllung.",
    "allergens": "Ask staff",
    "image": "images/desserts/red-bean-mochi.jpg"
  }
];
